apiVersion: v1
kind: ConfigMap
metadata:
    name: delivery-service-config
data:
    NODE_ENV: "production"
    PORT: "8080"
    DB_HOST: "delivery-postgres"
    DB_PORT: "5432"
    DB_NAME: "delivery_db"
    RABBITMQ_HOST: "rabbitmq"
    RABBITMQ_PORT: "5672"
